### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by curlysasha** [CiaraStrawberry/svd-temporal-controlnet#9]
```
(venv) C:\svd-temporal-controlnet>python run_inference.py
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.2+cu121 with CUDA 1201 (you have 2.1.2+cpu)
    Python  3.10.11 (you have 3.10.6)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
layers per block is 2
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:00<00:00, 25.25it/s]
Traceback (most recent call last):
  File "C:\svd-temporal-controlnet\run_inference.py", line 274, in <module>
    video_frames = pipeline(validation_image, validation_control_images[:14], decode_chunk_size=8,num_frames=14,motion_bucket_id=100,controlnet_cond_scale=1.0).frames
  File "C:\svd-temporal-controlnet\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\svd-temporal-controlnet\pipeline\pipeline_stable_video_diffusion_controlnet.py", line 441, in __call__
    image_embeddings = self._encode_image(image, device, num_videos_per_prompt, do_classifier_free_guidance)
  File "C:\svd-temporal-controlnet\pipeline\pipeline_stable_video_diffusion_controlnet.py", line 155, in _encode_image
    image = image.to(device=device, dtype=dtype)
  File "C:\svd-temporal-controlnet\venv\lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

and can you tell me where is downloaded models?

**Comment by curlysasha** [comment]
solution
`pip install torch torchvision -f https://download.pytorch.org/whl/torch_stable.html`

where is models stored?

**Comment by CiaraStrawberry** [comment]
This is a problem with your torch install rather than my repo, i have absolutely no clue how to fix it outside of just nuking the torch installation and reinstalling lol
